server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: rootpass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
